server:
  port: 4650

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.translate.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/ts/"
  application:
    name: Translation Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${TS_TRANSLATION_SERVICE_DB_HOST:localhost}:${TS_TRANSLATION_SERVICE_DB_PORT:6969}/${TS_TRANSLATION_SERVICE_DB_NAME:ts_translation_service}${TS_TRANSLATION_SERVICE_DB_OPTIONS:}
    username: ${TS_TRANSLATION_SERVICE_DB_USERNAME:postgres}
    password: ${TS_TRANSLATION_SERVICE_DB_PASSWORD:postgres}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: tsTranslationHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    out-of-order: true
    ignore-missing-migrations: true

azure:
  application-insights:
    instrumentation-key: ${ts.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
